#!/usr/bin/env python3
"""Generate notebooks/INDEX.md: one row per notebook, sorted by chapter.

Extracted per file: chapter label (from filename), frameworks (import scan),
model IDs referenced, cell count, and a RUNNABLE/CONCEPTUAL flag (a file whose
first code cell contains 'not runnable' is flagged CONCEPTUAL).

Deterministic: same input tree -> byte-identical INDEX.md.
Writes ONLY notebooks/INDEX.md.
"""
import json
import re
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent.parent / "notebooks"

FRAMEWORK_HINTS = {
    "google.adk": "Google ADK",
    "langchain": "LangChain",
    "langgraph": "LangGraph",
    "crewai": "CrewAI",
    "weaviate": "Weaviate",
    "fastmcp": "FastMCP",
    "mcp": "MCP",
    "openai": "OpenAI SDK",
    "google.genai": "google-genai",
    "vertexai": "Vertex AI",
    "pydantic": "Pydantic",
}
MODEL_RE = re.compile(r"['\"]((?:gemini|gpt|claude)[a-z0-9._-]{2,})['\"]")


def scan(path: Path) -> dict:
    nb = json.loads(path.read_text())
    src = "\n".join(
        "".join(c.get("source", []))
        for c in nb.get("cells", [])
        if c.get("cell_type") == "code"
    )
    frameworks = sorted({
        label for hint, label in FRAMEWORK_HINTS.items()
        # prefix match so e.g. `from langchain_openai import ...` counts as LangChain
        if re.search(rf"(?:^|\n)\s*(?:import|from)\s+{re.escape(hint)}(?![a-z])[\w.]*",
                     src.replace("langchain_", "langchain."))
    })
    models = sorted(set(MODEL_RE.findall(src)))
    conceptual = "not runnable" in src.lower()
    return {
        "name": path.name,
        "cells": len(nb.get("cells", [])),
        "frameworks": frameworks,
        "models": models,
        "flag": "CONCEPTUAL" if conceptual else "runnable",
    }


def chapter_key(name: str):
    m = re.match(r"Chapter (\d+)", name)
    if m:
        return (0, int(m.group(1)), name)
    if name.startswith("Appendix"):
        return (1, 0, name)
    return (2, 0, name)


def main() -> None:
    rows = [scan(p) for p in sorted(NB_DIR.iterdir())
            if p.is_file() and p.name != "INDEX.md"]
    rows.sort(key=lambda r: chapter_key(r["name"]))

    lines = [
        "# Notebook Index",
        "",
        "Generated by `tools/build_index.py`. Do not edit by hand — regenerate",
        "after any change to `notebooks/` (see handoff/docs/MAINTENANCE.md).",
        "",
        "| Notebook | Cells | Frameworks | Model IDs referenced | Status |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        name = r["name"].replace("|", "\\|")
        lines.append(
            f"| `{name}` | {r['cells']} | {', '.join(r['frameworks']) or '—'} "
            f"| {', '.join(r['models']) or '—'} | {r['flag']} |"
        )
    lines.append("")
    (NB_DIR / "INDEX.md").write_text("\n".join(lines))
    print(f"wrote INDEX.md rows={len(rows)}")


if __name__ == "__main__":
    main()
